const express = require('express');
const { optionalAuth, validateToken } = require('../middlewares/auth.middleware');
const { getOnboarding, saveOnboarding, resetInferredInterests } = require('../controllers/onboarding.controller');
const { recordEvents, getReadingHistory } = require('../controllers/event.controller');
const { getMyEntitlements } = require('../controllers/membership.controller');
const { getPostSummary } = require('../controllers/premium-content.controller');
const member = require('../controllers/member-experience.controller');
const billing = require('../controllers/billing.controller');
const notifications = require('../controllers/notification.controller');
const { assistWriting } = require('../controllers/writing-assistant.controller');

const router = express.Router();
router.get('/onboarding', validateToken, getOnboarding);
router.put('/onboarding', validateToken, saveOnboarding);
router.delete('/interests/inferred', validateToken, resetInferredInterests);
router.post('/events', optionalAuth, recordEvents);
router.get('/reading-history', validateToken, getReadingHistory);
router.get('/me/entitlements', validateToken, getMyEntitlements);
router.get('/posts/:postId/summary', validateToken, getPostSummary);
router.get('/workshops', optionalAuth, member.listWorkshops);
router.post('/workshops', validateToken, member.createWorkshop);
router.put('/workshops/:workshopId/registration', validateToken, member.registerWorkshop);
router.get('/creator-updates', validateToken, member.listCreatorUpdates);
router.post('/creator-updates', validateToken, member.createCreatorUpdate);
router.post('/creators/:creatorId/requests', validateToken, member.createCreatorRequest);
router.get('/creator-requests/received', validateToken, member.listReceivedRequests);
router.patch('/creator-requests/:requestId', validateToken, member.updateReceivedRequest);
router.get('/me/creator-support', validateToken, member.listMySupport);
router.put('/me/creator-support/:creatorId', validateToken, member.setCreatorSupport);
router.delete('/me/creator-support/:creatorId', validateToken, member.removeCreatorSupport);
router.post('/billing/checkout', validateToken, billing.startCheckout);
router.post('/billing/portal', validateToken, billing.openBillingPortal);
router.post('/billing/webhook', billing.stripeWebhook);
router.get('/notifications', validateToken, notifications.listNotifications);
router.put('/notifications/read-all', validateToken, notifications.markAllRead);
router.put('/notifications/:notificationId/read', validateToken, notifications.markNotificationRead);
router.post('/writing-assistant', validateToken, assistWriting);

module.exports = router;
