import { test, expect } from '@playwright/test'

for (const loggedIn of [false, true]) {
  test(`bottom navigation opens Shorts and the ${loggedIn ? 'member' : 'guest'} profile sheet`, async ({ page }) => {
    const privateReads = []
    await page.setViewportSize({ width: 325, height: 735 })
    await page.route(url => url.pathname.startsWith('/api/'), route => {
      const url = new URL(route.request().url())
      if (url.pathname === '/api/auth/refresh-token') return route.fulfill({ status: loggedIn ? 200 : 401, json: loggedIn ? { accessToken: 'navigation-token', user: 'Priya Mehta', email: 'member@inkrider.local', role: 'regular' } : { message: 'Signed out' } })
      if (url.pathname.startsWith('/api/user/') || url.pathname === '/api/v1/me/entitlements') privateReads.push(url.pathname)
      if (url.pathname === '/api/user/me') return route.fulfill({ json: { data: { displayName: 'Priya Mehta', handle: 'priya-mehta', bio: 'A curious reader.', joinedAt: '2025-01-15', postCount: 0, followersCount: 0, followingCount: 0 } } })
      if (url.pathname === '/api/v1/me/entitlements') return route.fulfill({ json: { data: { capabilities: [] } } })
      if (url.pathname === '/api/v1/notifications') return route.fulfill({ json: { data: [], meta: { unreadCount: 0 } } })
      return route.fulfill({ json: { data: [], meta: { nextCursor: null } } })
    })
    await page.goto('/')
    const nav = page.getByRole('navigation', { name: 'Mobile primary navigation' })
    await expect(nav.getByRole('link')).toHaveText(['Home', 'Explore', 'Shorts', 'Collections'])
    await expect(nav.getByRole('link', { name: 'Write', exact: true })).toHaveCount(0)
    await expect(nav.getByRole('link', { name: 'Explore', exact: true }).locator('svg')).toHaveAttribute('stroke', 'currentColor')
    await nav.getByRole('link', { name: 'Collections', exact: true }).click()
    await expect(page).toHaveURL(/\/collections$/)
    await expect(page.getByRole('heading', { name: 'Collections', exact: true })).toBeVisible()
    await expect(nav.getByRole('link', { name: 'Collections', exact: true })).toHaveAttribute('aria-current', 'page')
    await expect(nav.getByRole('link', { name: 'Write', exact: true })).toHaveCount(0)
    await nav.getByRole('link', { name: 'Explore', exact: true }).click()
    await expect(page).toHaveURL(/\/explore\/trending$/)
    await expect(nav.getByRole('link')).toHaveText(['Home', 'Explore', 'Shorts', 'Collections'])
    await nav.getByRole('link', { name: 'Shorts' }).click()
    await expect(page).toHaveURL(/\/shorts$/)
    await expect(nav.getByRole('link', { name: 'Shorts' })).toHaveAttribute('aria-current', 'page')
    await expect(nav.getByRole('link', { name: 'Collections', exact: true })).toBeVisible()
    await nav.getByRole('button', { name: 'Account' }).click()
    await expect(page).toHaveURL(/\/shorts$/)
    const sheet = page.getByRole('dialog', { name: 'Account', exact: true })
    await expect(sheet.getByRole('link', { name: 'Settings' })).toBeVisible()
    await expect(sheet.getByRole('button', { name: 'Help' })).toBeVisible()
    await expect(sheet.getByRole('link', { name: 'Write', exact: true })).toHaveCount(1)
    if (!loggedIn) {
      expect(privateReads).toEqual([])
      await expect(sheet.getByRole('link', { name: 'Sign Up' })).toBeVisible()
      await sheet.getByRole('button', { name: 'Sign In' }).click()
      await expect(page.getByRole('dialog', { name: 'Sign in to Ink Rider' })).toBeVisible()
  await expect(page).toHaveURL(/\/shorts$/)
    } else {
      await expect(sheet.getByRole('button', { name: 'Sign In' })).toHaveCount(0)
      await sheet.getByRole('link', { name: /My profile/ }).click()
      await expect(page).toHaveURL(/\/profile$/)
      await expect(page.getByRole('heading', { name: 'Priya Mehta', exact: true })).toBeVisible()
      await expect(page.getByRole('button', { name: 'Edit profile' })).toBeVisible()
      await expect(page.getByRole('button', { name: 'Open app settings' })).toHaveCount(0)
    }
  })
}

test('search results has no page search form and modal arrow submits the query', async ({ page }) => {
  await page.setViewportSize({ width: 325, height: 735 })
  await page.route(url => url.pathname.startsWith('/api/'), route => {
    const url = new URL(route.request().url())
    if (url.pathname === '/api/auth/refresh-token') return route.fulfill({ status: 401, json: { message: 'Signed out' } })
    if (url.pathname === '/api/search') return route.fulfill({ json: { data: { posts: [], writers: [], shorts: [] } } })
    return route.fulfill({ json: { data: [], meta: { nextCursor: null } } })
  })
  await page.goto('/search?q=science')
  await expect(page.getByRole('navigation', { name: 'Mobile primary navigation' }).getByRole('link', { name: 'Collections', exact: true })).toBeVisible()
  const main = page.getByRole('main')
  await expect(main.getByRole('textbox')).toHaveCount(0)
  await expect(main.getByRole('button', { name: 'Search', exact: true })).toHaveCount(0)
  await expect(main.getByRole('heading', { name: 'Search results' })).toBeVisible()
  await expect(main.getByRole('button', { name: 'Filters' })).toBeVisible()
  await page.getByRole('navigation', { name: 'Global navigation' }).getByRole('combobox').click()
  const dialog = page.getByRole('dialog', { name: 'Search Ink Rider' })
  await dialog.getByRole('combobox').fill('Travel')
  await expect(dialog.getByRole('button', { name: /View all results/ })).toHaveCount(0)
  const actions = dialog.getByRole('search').getByRole('button')
  await expect(actions.nth(0)).toHaveAttribute('aria-label', 'Close search')
  await expect(actions.nth(1)).toHaveAttribute('aria-label', 'Search')
  await dialog.getByRole('button', { name: 'Search', exact: true }).click()
  await expect(page).toHaveURL(/\/search\?q=Travel$/)
  await expect(dialog).toHaveCount(0)
  await page.setViewportSize({ width: 1280, height: 800 })
  await expect(page.getByRole('navigation', { name: 'Global navigation' }).getByRole('combobox')).toBeVisible()
  await expect(main.getByRole('textbox')).toHaveCount(0)
})
