import { test, expect } from '@playwright/test'

test.beforeEach(async ({ page }) => {
  await page.route(url => url.pathname.startsWith('/api/'), route => route.fulfill(
    new URL(route.request().url()).pathname === '/api/auth/refresh-token'
      ? { status: 401, json: { message: 'Signed out' } }
      : { json: { data: [], meta: { nextCursor: null } } },
  ))
})

for (const theme of ['light', 'dark']) {
  const opposite = theme === 'dark' ? 'light' : 'dark'
  const assertTheme = async (page, expected) => {
    await expect(page.locator('html')).toHaveClass(expected === 'dark' ? /dark/ : /^(?!.*\bdark\b)/)
  }

  test(`unsaved theme follows the ${theme} system and live changes; sidebar arrow inherits its label`, async ({ page }) => {
    await page.emulateMedia({ colorScheme: theme })
    await page.goto('/')
    await assertTheme(page, theme)
    const explore = page.getByRole('navigation', { name: 'Desktop primary navigation' }).getByRole('button', { name: 'Explore', exact: true })
    await expect(explore.locator('svg').first()).toHaveAttribute('stroke', 'currentColor')
    await expect.poll(() => explore.evaluate(element => getComputedStyle(element.querySelector('svg')).stroke === getComputedStyle(element).color)).toBe(true)
    expect(await page.evaluate(() => localStorage.getItem('ink-theme'))).toBeNull()
    await page.emulateMedia({ colorScheme: opposite })
    await assertTheme(page, opposite)
    await page.reload()
    await assertTheme(page, opposite)
    expect(await page.evaluate(() => localStorage.getItem('ink-theme'))).toBeNull()
    await page.goto('/explore/trending')
    await expect(explore.locator('svg').first()).toHaveCSS('stroke', opposite === 'dark' ? 'rgb(238, 236, 232)' : 'rgb(25, 25, 25)')
  })

  test(`explicit ${theme} choice overrides the system and persists across reload and routes`, async ({ page }) => {
    await page.emulateMedia({ colorScheme: opposite })
    await page.goto('/settings')
    await page.getByLabel('Theme', { exact: true }).click()
    await page.getByRole('option', { name: theme === 'dark' ? 'Dark' : 'Light', exact: true }).click()
    await assertTheme(page, theme)
    expect(await page.evaluate(() => localStorage.getItem('ink-theme'))).toBe(theme)
    await page.emulateMedia({ colorScheme: theme })
    await page.emulateMedia({ colorScheme: opposite })
    await assertTheme(page, theme)
    await page.reload()
    await assertTheme(page, theme)
    await page.goto('/login')
    await assertTheme(page, theme)
    await page.goto('/')
    await assertTheme(page, theme)
  })
}

for (const width of [320, 1280]) {
  test(`settings dropdowns and restored system theme at ${width}px`, async ({ page }, testInfo) => {
    await page.setViewportSize({ width, height: 568 })
    await page.emulateMedia({ colorScheme: 'light' })
    await page.goto('/settings')
    const theme = page.getByRole('combobox', { name: 'Theme', exact: true })
    const language = page.getByRole('combobox', { name: 'Language', exact: true })
    await expect(theme).toHaveText('Use system theme')
    await expect(page.getByRole('button', { name: 'Back', exact: true })).toHaveCount(0)
    await language.click()
    await expect(page.getByRole('listbox', { name: 'Language' })).toBeVisible()
    await expect(page.getByRole('listbox', { name: 'Language' })).toHaveAttribute('data-placement', 'bottom')
    const languageBounds = await language.boundingBox()
    const languageListBounds = await page.getByRole('listbox', { name: 'Language' }).boundingBox()
    expect(Math.abs(languageListBounds.y - languageBounds.y - languageBounds.height)).toBeLessThanOrEqual(1)
    await expect(page.getByRole('option', { name: 'English' })).toHaveAttribute('aria-selected', 'true')
    await language.press('Escape')
    await expect(language).toBeFocused()
    await expect(page.getByRole('listbox')).toHaveCount(0)
    await theme.press('Enter')
    await expect(theme).toBeFocused()
    await theme.press('End')
    await theme.press('Enter')
    await expect(theme).toHaveText('Dark')
    await expect(page.locator('html')).toHaveClass(/dark/)
    await theme.click()
    await page.getByRole('listbox', { name: 'Theme' }).evaluate(element => Promise.all(element.getAnimations().map(animation => animation.finished)))
    await page.screenshot({ path: testInfo.outputPath('settings-dropdown-dark.png') })
    await theme.press('Escape')
    await theme.press('ArrowDown')
    await theme.press('Home')
    await theme.press('Enter')
    await expect(theme).toHaveText('Use system theme')
    expect(await page.evaluate(() => localStorage.getItem('ink-theme'))).toBeNull()
    await expect(page.locator('html')).not.toHaveClass(/dark/)
    await page.emulateMedia({ colorScheme: 'dark' })
    await expect(page.locator('html')).toHaveClass(/dark/)
    await expect(theme).toHaveText('Use system theme')
    await page.reload()
    await expect(theme).toHaveText('Use system theme')
    await page.emulateMedia({ colorScheme: 'light' })
    await expect(page.locator('html')).not.toHaveClass(/dark/)
    await theme.click()
    const list = page.getByRole('listbox', { name: 'Theme' })
    await expect(list.getByRole('option')).toHaveText(['Use system theme', 'Light', 'Dark'])
    const bounds = await list.boundingBox()
    const triggerBounds = await theme.boundingBox()
    await expect(list).toHaveAttribute('data-placement', 'bottom')
    expect(Math.abs(bounds.y - triggerBounds.y - triggerBounds.height)).toBeLessThanOrEqual(1)
    expect(Math.abs(bounds.width - triggerBounds.width)).toBeLessThanOrEqual(1)
    expect(bounds.x).toBeGreaterThanOrEqual(0)
    expect(bounds.x + bounds.width).toBeLessThanOrEqual(width)
    await list.evaluate(element => Promise.all(element.getAnimations().map(animation => animation.finished)))
    await page.screenshot({ path: testInfo.outputPath('settings-dropdown-light.png') })
    await theme.press('Tab')
    await expect(page.getByRole('listbox')).toHaveCount(0)
    await expect(language).toBeFocused()
    await theme.focus()
    await theme.press('l')
    await theme.press('i')
    await theme.press('Enter')
    await expect(theme).toHaveText('Light')
    await language.click()
    await page.getByRole('heading', { name: 'App preferences' }).click()
    await expect(page.getByRole('listbox')).toHaveCount(0)
    await page.goto('/help')
    await expect(page.getByRole('button', { name: 'Back', exact: true })).toHaveCount(0)
  })
}

test('short-screen dropdown stays attached and scrolls; reduced motion remains immediate', async ({ page }) => {
  await page.setViewportSize({ width: 320, height: 360 })
  await page.emulateMedia({ reducedMotion: 'reduce' })
  await page.goto('/settings')
  const theme = page.getByRole('combobox', { name: 'Theme', exact: true })
  await theme.click()
  const list = page.getByRole('listbox', { name: 'Theme' })
  await expect(list).toBeVisible()
  const placement = await list.getAttribute('data-placement')
  const control = await theme.boundingBox()
  const options = await list.boundingBox()
  expect(Math.abs(placement === 'bottom' ? options.y - control.y - control.height : control.y - options.y - options.height)).toBeLessThanOrEqual(1)
  expect(await list.evaluate(element => parseFloat(getComputedStyle(element).animationDuration))).toBeLessThanOrEqual(0.001)
  await theme.press('End')
  await expect(list.getByRole('option', { name: 'Dark', exact: true })).toBeInViewport()
  await theme.press('Enter')
  await expect(theme).toHaveText('Dark')
  await expect(theme).toBeFocused()
  await expect(page.getByRole('dialog')).toHaveCount(0)
})
