const tagsData = [
    "3d printing",
    "accessibility design",
    "acoustics engineering",
    "agile methodologies",
    "ai ethics",
    "algorithm design",
    "alternative energy",
    "analytics",
    "anthropology",
    "app design",
    "ar/vr development",
    "architecture",
    "art & design",
    "artificial intelligence",
    "astrophysics",
    "automation",
    "backend frameworks",
    "behavioral science",
    "biochemistry",
    "bioengineering",
    "bioinformatics",
    "biotechnology",
    "blockchain development",
    "brand management",
    "business intelligence",
    "cad (computer-aided design)",
    "cognitive science",
    "cloud architecture",
    "cloud security",
    "computer vision",
    "content creation",
    "content management systems",
    "cryptography",
    "cultural studies",
    "cyber law",
    "cyber physical systems",
    "cyber-physical security",
    "data analytics",
    "data engineering",
    "data mining",
    "data privacy",
    "data visualization",
    "database administration",
    "deep learning",
    "design systems",
    "digital art",
    "digital ethics",
    "digital forensics",
    "digital humanities",
    "digital transformation",
    "distributed systems",
    "e-learning development",
    "e-sports",
    "economic modeling",
    "educational technology",
    "electronics engineering",
    "embedded programming",
    "energy storage",
    "entrepreneurship",
    "environmental science",
    "ethical hacking",
    "evolutionary computation",
    "finance technology (fintech)",
    "geospatial analysis",
    "green technology",
    "healthcare it",
    "high performance computing",
    "human-centered design",
    "human-robot interaction",
    "industrial automation",
    "information security",
    "interactive design",
    "knowledge management",
    "language processing",
    "legal technology",
    "linguistics",
    "logistics technology",
    "machine vision",
    "marine technology",
    "mathematical modeling",
    "media studies",
    "medical imaging",
    "mobile app analytics",
    "mobile security",
    "music technology",
    "nanoengineering",
    "nanotechnology",
    "network engineering",
    "network protocols",
    "neural networks",
    "nuclear engineering",
    "object-oriented programming",
    "online security",
    "operating systems",
    "parallel computing",
    "penetration testing",
    "performance optimization",
    "photovoltaics",
    "physics simulations",
    "policy informatics",
    "political science",
    "programming languages",
    "quantum information science",
    "quantum mechanics",
    "quantum programming",
    "recommender systems",
    "renewable energy",
    "risk management",
    "robotics engineering",
    "satellite technology",
    "scientific computing",
    "search engine marketing",
    "semantic web",
    "smart cities",
    "smart grids",
    "social computing",
    "social media analysis",
    "software development life cycle (sdlc)",
    "speech recognition",
    "sports analytics",
    "supply chain technology",
    "sustainable development",
    "systems design",
    "tech ethics",
    "technology law",
    "telecommunications",
    "telemedicine",
    "theoretical computer science",
    "urban informatics",
    "user interface design",
    "ux research",
    "virtual assistants",
    "wearable technology",
    "web application security",
    "web frameworks",
    "web performance optimization",
    "wireless communication",
    "workflow automation",
    "zoology informatics"
];

export default tagsData;